dist: bionic

language: minimal

#FROM https://github.com/openhab/openhab-docker/blob/c5e586be529a9d3645e91962eba1ae20c3067cf8/.travis.yml#L16-L28
before_install:
  # Configure environment so changes are picked up when the Docker daemon is restarted after upgrading
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  # Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.8~3-0~ubuntu-bionic # pin version for reproducibility
  # Show info to simplify debugging and create a builder
  - docker info
  - docker buildx create --name builder --use
  - docker buildx ls

jobs:
  include:
    - os: linux
      arch: amd64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx build --platform linux/arm/v7 -t brunoshiroma/go-proxy:armv7-latest --push .

#after_succes:
#  script:
#    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#    - docker manifest create brunoshiroma/benchtool-java:latest brunoshiroma/benchtool-java:amd64-latest brunoshiroma/benchtool-java:arm64-latest
#    - docker push brunoshiroma/benchtool-java:latest