dist: bionic

language: go

go:
  - "1.14.6"

#FROM https://github.com/openhab/openhab-docker/blob/c5e586be529a9d3645e91962eba1ae20c3067cf8/.travis.yml#L16-L28
before_install:
  # Configure environment so changes are picked up when the Docker daemon is restarted after upgrading
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  # Upgrade to Docker CE 19.03 for BuildKit support
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce=5:19.03.8~3-0~ubuntu-bionic # pin version for reproducibility
  # Show info to simplify debugging and create a builder
  - docker info
  - docker buildx create --name builder --use
  - docker buildx ls

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - stage: compile
      name: GO Compile
      os: linux
      arch: amd64
      script:
          - go build cmd/go-proxy/main.go
    - stage: test
      name: GO Test
      os: linux
      arch: amd64
      script:
          - go test ./...
    - stage: test
      name: Docker build
      os: linux
      arch: amd64
      script:
          - docker buildx build --platform linux/amd64 .
    - stage: deploy
      name: Docker Build and Repository Push
      if: branch = main and type = push
      os: linux
      arch: amd64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx build --platform linux/arm/v7 -t brunoshiroma/go-proxy:armv7-latest --push .
        - docker buildx build --platform linux/arm/v6 -t brunoshiroma/go-proxy:armv6-latest --push .
        - docker buildx build --platform linux/amd64 -t brunoshiroma/go-proxy:amd64-latest --push .
        - docker buildx build --platform linux/arm64/v8 -t brunoshiroma/go-proxy:aarch64-latest --push .
        - docker buildx build --platform linux/386 -t brunoshiroma/go-proxy:386-latest --push .
        - docker manifest create brunoshiroma/go-proxy:latest brunoshiroma/go-proxy:386-latest brunoshiroma/go-proxy:armv7-latest brunoshiroma/go-proxy:armv6-latest brunoshiroma/go-proxy:amd64-latest brunoshiroma/go-proxy:aarch64-latest
        - docker manifest push brunoshiroma/go-proxy:latest