dist: bionic

language: java

services:
  - docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

jobs:
  include:
    - os: linux
      arch: amd64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx --platform linux/arm/v7 -t brunoshiroma/go-proxy:armv7-latest .
        - docker push brunoshiroma/go-proxy:armv7-latest

#after_succes:
#  script:
#    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#    - docker manifest create brunoshiroma/benchtool-java:latest brunoshiroma/benchtool-java:amd64-latest brunoshiroma/benchtool-java:arm64-latest
#    - docker push brunoshiroma/benchtool-java:latest