dist: focal

language: go

go:
  - "1.17"

#https://docs.docker.com/engine/install/ubuntu/ for the buildx
before_install:
  - sudo apt-get remove -y docker docker.io
  - sudo rm -rf /etc/default/docker
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - sudo echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce docker-ce-cli containerd.io

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - stage: compile
      name: GO Compile
      os: linux
      arch: amd64
      script:
          - go build cmd/go-proxy/main.go
    - stage: test
      name: GO Test
      os: linux
      arch: amd64
      script:
          - go test ./...
    - stage: test
      name: Docker build
      os: linux
      arch: amd64
      script:
          - docker buildx build --platform linux/amd64 .
    - stage: deploy
      name: Docker Build and Repository Push
      if: branch = main and type = push
      os: linux
      arch: amd64
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker buildx build --platform linux/arm/v7 -t brunoshiroma/go-proxy:armv7-latest --push .
        - docker buildx build --platform linux/arm/v6 -t brunoshiroma/go-proxy:armv6-latest --push .
        - docker buildx build --platform linux/amd64 -t brunoshiroma/go-proxy:amd64-latest --push .
        - docker buildx build --platform linux/arm64/v8 -t brunoshiroma/go-proxy:aarch64-latest --push .
        - docker buildx build --platform linux/386 -t brunoshiroma/go-proxy:386-latest --push .
        - docker manifest create brunoshiroma/go-proxy:latest brunoshiroma/go-proxy:386-latest brunoshiroma/go-proxy:armv7-latest brunoshiroma/go-proxy:armv6-latest brunoshiroma/go-proxy:amd64-latest brunoshiroma/go-proxy:aarch64-latest
        - docker manifest push brunoshiroma/go-proxy:latest