FROM golang:alpine AS build-base
RUN apk update && apk upgrade
RUN apk add build-base

FROM build-base as build
WORKDIR /proxy
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' ./cmd/go-proxy/

FROM alpine AS runtime
RUN apk update && apk upgrade
WORKDIR /proxy
COPY --from=build /proxy/go-proxy .
ENTRYPOINT ["./go-proxy"]
