name: CI

jobs:
    build:
      runs-on: ubuntu-latest
      name: build
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.14.2
        - run: go build -a -ldflags '-extldflags "-static"' ./cmd/go-proxy/
    test:
      runs-on: ubuntu-latest
      name: test
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.14.2
        - run: go test ./...