name: CI

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      name: build
      steps:
        - uses: actions/checkout@v4
        - name: Setup go
          uses: actions/setup-go@v5
          with:
            go-version: 1.22
        - run: go build ./...
    test:
      runs-on: ubuntu-latest
      name: test
      steps:
        - uses: actions/checkout@v4
        - name: Setup go
          uses: actions/setup-go@v5
          with:
            go-version: 1.22
        - run: go test ./...
